spring:
  application:
    name: products


  data:
    mongodb:
      database: KangooDB
      host: localhost
      port: 27017

cors:
  allowedOrigins: 'http://localhost:5173'

logging:
  level:
    web: debug

server:
  port: 8081