spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: dbuser
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
