spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_data
    username: db_user
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      ddl-auto: update
  jpa:
    open-in-view: false
  rabbitmq:
    password: Password123!
    username: amqp_user
    vhost: Kangoo_local
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      password: Password123!
      ssl:
        enabled: false

logging:
  level:
    dev.kangoo: debug

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
