spring:
  application:
    name: customers

  data:
    mongodb:
      database: KangooDB
      host: localhost
      port: 27017

cors:
  allowedOrigins: 'http://localhost:5173'

security:
  pepper: MY_SECURE_PEPPER

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_0

server:
  port: 8081