name: Auth Service Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/auth/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build the project
      - name: Build with Maven
        run: mvn -B package --file ./backend/auth/pom.xml
